### ISSUE TITLE
Received ERR_STREAM_WRITE_AFTER_END error when running stream_player.js

### ISSUE THREAD

**Issue by timezombi** [Unity-Technologies/ucs-diag-utils#4]
I encountered a strange error when using stream_player.js to replay a client recording of ~200MB with concurrency set to 6.

Under normal circumstances, it runs in about 30 seconds. After encountering the error, it did nothing for over 20 minutes. Killing `stream_player.js` and retrying succeeded but several subsequent runs also failed.

Just rerunning `stream_player.js` a few times was consistently reproducing it. Restarting the cache server does not prevent the error from occuring.

Example:

> $ ./stream_player.js -c 20 -i 6 ../unity-cache-server/diagnostics/client-recordings/847cb284-fcf2-436e-90e8-34a82aa70edd 127.0.0.1:8127
> [6/6] Playing ../unity-cache-server/diagnostics/client-recordings/847cb284-fcf2-436e-90e8-34a82aa70edd
> [6/6] Playing ../unity-cache-server/diagnostics/client-recordings/847cb284-fcf2-436e-90e8-34a82aa70edd
> [6/6] Playing ../unity-cache-server/diagnostics/client-recordings/847cb284-fcf2-436e-90e8-34a82aa70edd
> [6/6] Playing ../unity-cache-server/diagnostics/client-recordings/847cb284-fcf2-436e-90e8-34a82aa70edd
> [6/6] Playing ../unity-cache-server/diagnostics/client-recordings/847cb284-fcf2-436e-90e8-34a82aa70edd
> [6/6] Playing ../unity-cache-server/diagnostics/client-recordings/847cb284-fcf2-436e-90e8-34a82aa70edd
> Error [ERR_STREAM_WRITE_AFTER_END]: write after end
>     at writeAfterEnd (_stream_writable.js:243:12)
>     at Socket.Writable.write (_stream_writable.js:291:5)
>     at ClientStreamProcessor.ondata (_stream_readable.js:689:20)
>     at ClientStreamProcessor.emit (events.js:189:13)
>     at ClientStreamProcessor.Readable.read (_stream_readable.js:487:10)
>     at flow (_stream_readable.js:953:34)
>     at Socket.pipeOnDrainFunctionResult (_stream_readable.js:757:7)
>     at Socket.emit (events.js:189:13)
>     at onwriteDrain (_stream_writable.js:490:12)
>     at afterWrite (_stream_writable.js:478:5)

Sometimes I will still get the error but I will be returned cleanly to the terminal. When this happens, it still prints the "Sent XX GB in YY seconds" message.

**Comment by timezombi** [comment]
This client recording was not unique. I was able to repro the issue with other client recordings.
